In [2]:
import torch

D:\Work\Anaconda3\envs\bert\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [16]:
a = torch.randint(1, 5, (2, 3))
b = torch.randint(1, 5, (2, 3))
print(a)
print(b)

tensor([[4, 4, 4],
        [4, 1, 3]])
tensor([[2, 1, 1],
        [1, 4, 4]])


In [17]:
a + b #对应相加

tensor([[6, 5, 5],
        [5, 5, 7]])

In [18]:
torch.add(a, b)

tensor([[6, 5, 5],
        [5, 5, 7]])

In [19]:
result = torch.zeros(2, 3)
torch.add(a,b,out = result)

tensor([[6., 5., 5.],
        [5., 5., 7.]])

In [20]:
#a = a + b
#注意任何张量tensor会发生变换的操作都有一个前缀_
a.add_(b)

tensor([[6, 5, 5],
        [5, 5, 7]])

In [21]:
a - b

tensor([[4, 4, 4],
        [4, 1, 3]])

In [23]:
print(a)
print(b)
a * b

tensor([[6, 5, 5],
        [5, 5, 7]])
tensor([[2, 1, 1],
        [1, 4, 4]])


tensor([[12,  5,  5],
        [ 5, 20, 28]])

In [27]:
tensor = torch.ones(3 ,5, dtype = int)
tensor

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [28]:
torch.matmul(a, tensor) #矩阵的乘法

tensor([[16, 16, 16, 16, 16],
        [17, 17, 17, 17, 17]])

In [29]:
a.T #矩阵的转置

tensor([[6, 5],
        [5, 5],
        [5, 7]])

In [43]:
sample = torch.rand(3, 2, 5)
sample

tensor([[[0.1342, 0.1608, 0.8801, 0.0534, 0.8958],
         [0.9503, 0.7246, 0.0279, 0.9716, 0.2352]],

        [[0.2498, 0.2274, 0.8409, 0.5691, 0.6348],
         [0.0901, 0.2153, 0.1953, 0.3492, 0.7765]],

        [[0.4764, 0.9894, 0.7057, 0.8733, 0.8762],
         [0.9012, 0.9755, 0.0949, 0.4441, 0.9953]]])

In [44]:
torch.sum(sample) #求和

tensor(16.5144)

In [45]:
torch.min(sample)

tensor(0.0279)

In [46]:
torch.max(sample)

tensor(0.9953)

In [47]:
#求最小值所在的位置(索引)
torch.argmin(sample)
torch.argmax(sample)

tensor(29)

In [48]:
torch.mean(sample)

tensor(0.5505)

In [49]:
torch.median(sample)

tensor(0.5691)

In [50]:
torch.sqrt(sample)

tensor([[[0.3663, 0.4009, 0.9382, 0.2311, 0.9465],
         [0.9748, 0.8513, 0.1671, 0.9857, 0.4849]],

        [[0.4998, 0.4769, 0.9170, 0.7544, 0.7968],
         [0.3001, 0.4640, 0.4420, 0.5909, 0.8812]],

        [[0.6902, 0.9947, 0.8401, 0.9345, 0.9361],
         [0.9493, 0.9877, 0.3081, 0.6664, 0.9976]]])

In [52]:
sample ** 2 #乘方
sample

tensor([[[0.1342, 0.1608, 0.8801, 0.0534, 0.8958],
         [0.9503, 0.7246, 0.0279, 0.9716, 0.2352]],

        [[0.2498, 0.2274, 0.8409, 0.5691, 0.6348],
         [0.0901, 0.2153, 0.1953, 0.3492, 0.7765]],

        [[0.4764, 0.9894, 0.7057, 0.8733, 0.8762],
         [0.9012, 0.9755, 0.0949, 0.4441, 0.9953]]])