In [1]:
import torch

D:\Work\Anaconda3\envs\bert\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tensor = torch.arange(2, 14)
tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
print(tensor[1:4])

tensor([3, 4, 5])


In [5]:
print(tensor[2:-1])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])


In [6]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [7]:
print(tensor[-3:-1])

tensor([11, 12])


In [8]:
index = [1, 3, 4, 5, 5]
tensor[index]

tensor([3, 5, 6, 7, 7])

In [10]:
for t in tensor:
    print(t)

tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)
tensor(10)
tensor(11)
tensor(12)
tensor(13)
